### 전화번호 인증 요청
POST http://127.0.0.1:8000/mobileauth/
Content-Type: application/json

{
  "name": "테스터",
  "phone": "010-0000-0000"
}

### 전환번호 인증
PUT http://127.0.0.1:8000/mobileauth/3/certified/
Content-Type: application/json

{
  "authorization_number": "2212"
}

### 회원가입
POST http://127.0.0.1:8000/members/
Content-Type: application/json

{
  "mobileAuthId": 4,
  "email": "test@test.com",
  "nickname": "test123",
  "password": "1234",
  "name": "테스터",
  "phone": "010-0000-0000"
}

### 로그인
POST http://127.0.0.1:8000/members/login/
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234",
  "phone": "010-0000-0000"
}

### 정보 보기
GET http://127.0.0.1:8000/members/3/
A-Token: 43597c32dbaec99bdf8e1fe69ab75391bddd7a1d1747ca1e227fdf93f408273a

### 비밀번호 재설정
PUT http://127.0.0.1:8000/members/3/password-reset/
Content-Type: application/json

{
  "mobileAuthId": 2,
  "password": "5678",
  "phone": "010-0000-0000"
}


